### PR TITLE
Fix sample code for common performance section

### PR DESCRIPTION
**Pull request by chadedrupt**
Updates the js samples to be referenced as common-js.

And also includes sample code for Objective-C and Swift.

Will be able to add the other language samples soon.

### CODE REVIEW

**Comment by hramos** [comment]
This is great!

One nit: can you update the swift code block tags to be common-swift as well?

**Comment by chadedrupt** [comment]
Done. not sure how I missed them 😄 Thanks

**Comment by hramos** [comment]
Awesome, this all looks good to go. One last thing if you don't mind, can you squash these three commits into one?

You should be able to do so by running:

     $ git rebase -i HEAD~3

Since these commits are already associated with this pull request, you may need to use --force when pushing them:

     $ git push origin --force

**Comment by chadedrupt** [comment]
There we go.

**Pull request merged**
