### PR TITLE
Add Swift example to "Loading remote images in cells"

### PR DESCRIPTION
**Pull request by delux75**

### CODE REVIEW

**Comment by hramos** [comment]
Can you resolve the conflicts?

**Comment by delux75** [comment]
Done.

**Comment by hramos** [comment]
It looks like there's two copies of the same cell loading method for Swift, is that intentional?

**Comment by delux75** [comment]
J just notice. Apparently since my pull request someone has provided an example. So I guess my pull request is irrelevant now ^_^

**Comment by hramos** [comment]
Ahh, I see. I appreciate your contribution nonetheless!

**Comment by delux75** [comment]
Thanks ;) I'll try to be faster next time.

**Pull request closed without merging**
