### PR TITLE
Adding Microsoft OAuth Documentation

### PR DESCRIPTION
**Pull request by alann-maulana**
Referring #692 from @TomWFox

### CODE REVIEW

**Comment by alann-maulana** [comment]
I'm curious why this `assets/js/bundle.js` included automatically? Is this my mistake, again? 😅

**Comment by dplewis** [comment]
You don’t have to worry about that. When the PR is merged the bundle will be regenerated anyway

**Comment by alann-maulana** [comment]
> You don’t have to worry about that. When the PR is merged the bundle will be regenerated anyway

@dplewis ahh great, because suddenly I'm closing this PR #697 because of `assets/js/bundle.js` accidentally included at my commit

**Comment by dplewis** [comment]
You can just leave. Look at previous PRs they all include it.

**Comment by dplewis** [comment]
Nvm I wondered why this PR looked familiar.

**Review by TomWFox — APPROVED** [review]
Thanks for the PR, sorry for the delay, looks good to me!

**Comment by TomWFox** [comment]
Merging as 3.10 has been released.

**Pull request merged**
