### PR TITLE
Remove a bunch of parse cloud references

### PR DESCRIPTION
**Pull request by TomWFox**

### CODE REVIEW

**Comment by TomWFox** [comment]
This isn’t finished but I want to get these changes in, will continue soon

**Comment by davimacedo** [comment]
Wouldn't it be better to have someone else reviewing before merging?

**Comment by TomWFox** [comment]
Maybe, I just felt these changes were very minor so didn’t warrant review. But I’ll happily make any changes if you find any issues.

**Comment by TomWFox** [comment]
Me and @acinader have discussed what changes could be made without review but maybe we should discuss that properly

**Comment by davimacedo** [comment]
Or maybe we could have the best practices written down in some doc of the Governance repo.

**Comment by TomWFox** [comment]
I agree

**Pull request merged**
