### PR TITLE
add note to JS users class docs about logIn usePost option

### PR DESCRIPTION
**Pull request by kolohelios**
https://github.com/parse-community/Parse-SDK-JS/pull/1229

### CODE REVIEW

**Comment by TomWFox** [comment]
Thanks for the PR!

**Comment by dplewis** [comment]
Probably add the SDK version that will support this.

**Comment by kolohelios** [comment]
Good call. Will the next release be at v2.17.0?

**Comment by dplewis** [comment]
Most likely

**Review by TomWFox — APPROVED** [review]

**Pull request merged**
