### PR TITLE
query.aggregate() doesn't need find()

### PR DESCRIPTION
**Pull request by oallouch**
The implementation might have changed.

### CODE REVIEW

**Review by flovilmart — APPROVED** [review]

**Comment by flovilmart** [comment]
@dplewis can you confirm?

**Comment by dplewis** [comment]
@flovilmart This is correct. It was discussed here https://github.com/parse-community/parse-server/issues/4640#issuecomment-373404553 but I haven't had time to get to updating the docs.

**Review by dplewis — APPROVED** [review]

**Comment by oallouch** [comment]
I did a PR ! I did a PR !

**Comment by dplewis** [comment]
@flovilmart Can we get this in? I don't have permission.

**Comment by flovilmart** [comment]
Congrats @oallouch ! That's a good one indeed!

**Comment by joshkopecek** [comment]
@dplewis very happy this made it across from [parse-community/parse-server#4640 (comment)](https://github.com/parse-community/parse-server/issues/4640#issuecomment-373404553)!

**Comment by oallouch** [comment]
@joshkopecek  No complicated local clone, just a github edit (which creates a PR).

**Pull request merged**
