### PR TITLE
Add Pointer Permission docs.

### PR DESCRIPTION
**Pull request by drew-gross**
GitHub doesn't allow commandeering like Phab does, so this pull request replaces https://github.com/ParsePlatform/Docs/pull/89 from Jamie. I removed the reference to CLP-ACL interaction docs in favor of a short description of the interaction. I'll add it back once we recover that section from the old docs.

### CODE REVIEW

**Comment by hramos** [comment]
LGTM @drew-gross. Feel free to merge in when you want this to be deployed.

**Comment by drew-gross** [comment]
@hramos I don't have write access on this account/repo.

**Comment by drew-gross** [comment]
@hramos I decided it would be worthwhile to rescue the old security docs now - want to give this another once-over?

**Comment by hramos** [comment]
LGTM

**Pull request merged**
