### PR TITLE
Squash from #41, Solved conflicts on notification codes;

### PR DESCRIPTION
**Pull request by Lucashuang0802**
Link #21 and #41

### CODE REVIEW

**Comment by nlutsenko** [comment]
@Lucashuang0802 Sorry, took me a while to get back to you.
Can you rebase the commit on master so it's mergeable?

**Comment by Lucashuang0802** [comment]
Sure, I will take some time to rebase it and fix it tonight.

**Comment by nlutsenko** [comment]
@Lucashuang0802 Awesome, thank you! Everything else looks great!

**Comment by Lucashuang0802** [comment]
Okay, I will comment it once I am done with it.

**Comment by Lucashuang0802** [comment]
Finished the type fixes and rebase. Code can be merged to the master branch right now.

**Comment by nlutsenko** [comment]
Perfect! Ready to merge in!
One last thing, could you squash all these things together so it's 1 commit?
This helps us keep the repo history clean, as `merge branch master into swift-ios-update` is not really helpful when you look at the history... :)

**Comment by Lucashuang0802** [comment]
I will just create another pull request and I will delete the previous after merging. That's more easier.

**Comment by Lucashuang0802** [comment]
Link #73

**Comment by nlutsenko** [comment]
Superseeded by #73

**Pull request closed without merging**
