### PR TITLE
Update algolia apiKey

### PR DESCRIPTION
**Pull request by QuentinDela**

### CODE REVIEW

**Review by flovilmart — APPROVED** [review]

**Comment by hramos** [comment]
How was this key generated, and is it tied to a paid plan?

**Comment by QuentinDela** [comment]
I asked for one on support@algolia.com

**Comment by hramos** [comment]
Thanks Quentin, I chatted with them and they let me know. They reactivated the original key so we're good now.

**Comment by flovilmart** [comment]
So? Revert?

**Comment by hramos** [comment]
@flovilmart already happened :)

**Pull request merged**
