### PR TITLE
feat: make doc links dynamic

### LINKED ISSUE #932: Fix docs page
### Issue

The docs page (https://docs.parseplatform.org) is an outdated version of the main page's section of docs (https://parseplatform.org). Both are maintained separately, which is difficult and causes one of them to be now outdated.

The outdated https://docs.parseplatform.org is visited more than the main page https://parseplatform.org, because for developers searching for docs online the https://docs.parseplatform.org  has a higher ranking in search results.

### Solution

De-duplicate both pages.

### PR DESCRIPTION
**Pull request by dblythy**
Currently, the doc links are fixed. This can be changed by building them dynamically.

The file `js/links` could be served either here or on `parseplatform.org`.

Related: https://github.com/parse-community/parse-community.github.io/pull/49

Closes #932

### CODE REVIEW

**Comment by dblythy** [comment]
The one file used by both sites will create a more consistent docs link experience.

Screenshot 2023-06-12 at 7 01 30 pm

Screenshot 2023-06-12 at 7 02 50 pm

**Review by mtrezza — APPROVED** [review]
Looks good, can this be merged? Or should we wait for https://github.com/parse-community/parse-community.github.io/pull/49 to be ready, just in case?

**Comment by dblythy** [comment]
We do [#49](https://github.com/parse-community/parse-community.github.io/pull/49) first, and then add a script tag pointing to the `links` file at `parseplatform.org`

**Comment by mtrezza** [comment]
Merged https://github.com/parse-community/parse-community.github.io/pull/49

**Comment by dblythy** [comment]
Cool, this is good to merge

**Pull request merged**
