### PR TITLE
Update docs to mirror the server readme

### PR DESCRIPTION
**Pull request by ghost**
Saw it mentioned in https://github.com/parse-community/parse-server/issues/275 a few times, and took me a while to find it, so updating here too. Not sure what the longer term plans are regarding docs, seems to be multiple places for the same docs

### CODE REVIEW

**Comment by flovilmart** [comment]
Good idea! Ideally we’d need to centralize it all :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by flovilmart** [comment]
@thedevworks I started a branch to rebuild the docs with docusaurus and most probably merging all web properties on the same one. Is it something you’d like to participate in?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ghost** [comment]
Yeah for sure! I can free up a bit of time for it

**Comment by flovilmart** [comment]
Awesome!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
