### PR TITLE
docs: add requireAnyUserRoles and requireAllUserRoles on cloud validator

### PR DESCRIPTION
**Pull request by dblythy**
Documentation for [7097](https://github.com/parse-community/parse-server/pull/7097)

### CODE REVIEW

**Review by TomWFox — APPROVED** [review]
LGTM 👍

**Review by davimacedo — APPROVED** [review]
LGTM!

**Comment by dblythy** [comment]
Ready for merge

**Review by mtrezza — APPROVED** [review]
Thanks for looking at these open doc PRs!

**Pull request merged**
