### PR TITLE
updated afterSave with promises

### PR DESCRIPTION
**Pull request by thobhanifreddy**
As a part of https://github.com/parse-community/docs/issues/556 I tried a updating afterSave with promises. Can someone please review it and suggest any improvements? Looking forward to updated other parts if this PR is upto the point.

### CODE REVIEW

**Comment by flovilmart** [comment]
When using afterSave with await, you’ll be blocking the response sent to the client till your async method completes.

Is that what you intended?

**Comment by thobhanifreddy** [comment]
@flovilmart I thought async/await is cleaner than `.then`. Otherwise they work almost the same.

**Comment by flovilmart** [comment]
> I thought async/await is cleaner than .then. Otherwise they work almost the same.

I believe the key word is *almost*. 

consider the following:

```
function myAfterSave0(req) {
    const query = new Parse.Query();
    query.find().then((results) => {
        // do something...
   })
} 
function myAfterSave1(req) {
    const query = new Parse.Query();
    // return the promise
    return query.find().then((results) => {
        // do something...
   })
}

async function myAfterSave2(req) {
    const query = new Parse.Query();
    // await the results
    const results =  await query.find();
    /// do something
} 
```

Now imagine I call those 3 functions and insect the object

```
const res0 = myAfterSave0()
const res1 = myAfterSave1()
const res2 = myAfterSave2()
```

- [ ] `typeof res0 === 'undefined'`
- [ ] `res0 instanceof Promise`
- [ ] `typeof res1 === 'undefined'`
- [ ] `res1 instanceof Promise`
- [ ] `typeof res2 === 'undefined'`
- [ ] `res2 instanceof Promise`

In afterSave parse-server checks the type that is retuned from the handler. if the handler returns a promise, then the server will wait till the promises resolves.

So while it's almost the same it isn't.

**Comment by acinader** [comment]
i think #578 addresses this in a better way, i think we can close this and we'll resolve via working out #578 @thobhanifreddy let me know if you think that we should re-open this instead....

**Pull request closed without merging**
