### PR TITLE
docs: Add JS doc for `Parse.Object.revert()`

### PR DESCRIPTION
**Pull request by NicksonYap**

### CODE REVIEW

**Comment by NicksonYap** [comment]
https://github.com/parse-community/Parse-SDK-JS/issues/323

**Comment by flovilmart** [comment]
@NicksonYap thanks for the PR. Does it really fit into the performance section?

**Comment by NicksonYap** [comment]
@flovilmart  you're welcome.

I'm not certain
I think it doesn't but I suppose it can be considered as Client-side caching?
Don't know what name to call this behaviour
To be honest I don't know what's the use of replacing server-side data with client-side data
Since calling `find()` or `get()` the object will trigger an API call anyways

**Comment by flovilmart** [comment]
This isn’t caching. This feature is simply about discarding any changed keys from the client. The use of replacing server side data, is basically the core feature of parse, which is saving and updating objects

**Comment by TomWFox** [comment]
I wonder whether this would make sense in the data section.

Also could we get code samples for the other client SDKs as well?

**Comment by mtrezza** [comment]
I'l go ahead and merge this; could be helpful; fixed husky along the way...

**Comment by NicksonYap** [comment]
Okie, I haven't been in the project for so long i don't recall what this is, all the best!

**Review by mtrezza — APPROVED** [review]

**Pull request merged**
