### PR TITLE
document push type and priority keys for notifications

### PR DESCRIPTION
**Pull request by funkenstrahlen**
This is related to these PR in parse server push adapter:

* https://github.com/parse-community/parse-server-push-adapter/pull/127
* https://github.com/parse-community/parse-server-push-adapter/pull/128

### CODE REVIEW

**Review by davimacedo — COMMENTED** [review]
Do you mind to also include [here](http://docs.parseplatform.org/js/guide/#sending-options)?

**Comment by funkenstrahlen** [comment]
Sure I can do that. Thanks for pointing this out.

**Comment by funkenstrahlen** [comment]
As suggested I added the push type and priority key explanation to the JS docs as well.

**Review by davimacedo — APPROVED** [review]

**Comment by davimacedo** [comment]
@TomWFox let's wait for https://github.com/parse-community/parse-server-push-adapter/pull/127 and merge.

**Review by TomWFox — APPROVED** [review]

**Comment by funkenstrahlen** [comment]
This is ready to merge now as the new functionality is merged into Parse push adapter.

**Pull request merged**
