### PR TITLE
Finished Swift iOS docs for #21

### PR DESCRIPTION
**Pull request by Lucashuang0802**
I have finished updating the items listed from #21. Please leave me comments if there are changes I need to make regarding to coding style or the way it presents the functionalities. I pretty much stick with the style from other Parse's Swift code

### CODE REVIEW

**Comment by Lucashuang0802** [comment]
Got it

**Comment by nlutsenko** [comment]
A lot of nits. Generally - these apply to everything, but I might have missed few points where these are applicable. Will take a look after these are fixed.

**Comment by Lucashuang0802** [comment]
Just made some changes on it and already took a look at other files. Let me know if something was still not consistent.

**Comment by nlutsenko** [comment]
Any chance you can squash all these changes into a single commit?
It's quite hard to review changes apart from each other.

**Comment by Lucashuang0802** [comment]
handling-errors.mdown: applied "If statments and forced unwrapping" on `result` and `error`: `if let result = result {`  `if let error = error {`

**Comment by Lucashuang0802** [comment]
i will write that one by one

**Comment by nlutsenko** [comment]
Unwrapping through `if let result = result` is perfect - that works great.
Would love to see the squashed commit here so we can review full set of changes and merge it in!
Keep it up!

**Comment by Lucashuang0802** [comment]
Ah, yup. I skipped that in local-datastore.mdown. I will just make changes right away and write comments for every single files.

**Comment by nlutsenko** [comment]
Sounds great! Looking forward to see them!

**Comment by Lucashuang0802** [comment]
handling-errors.mdown: applied “If statements and forced unwrapping” on `result` and `error`

**Comment by Lucashuang0802** [comment]
in-app-purchases.mdown: applied trailing closure and put parameter list from another line

**Comment by Lucashuang0802** [comment]
local-datastore.mdown: applied “If statements and forced unwrapping” on `task.error`; applied trailing closure and put parameter list from another line

**Comment by Lucashuang0802** [comment]
queries.mdown: applied trailing closure and put parameter list from another line

**Comment by Lucashuang0802** [comment]
user-interface.mdown: applied “If statements and forced unwrapping” on `object[“title”]` on table view delegate method

**Comment by Lucashuang0802** [comment]
More than welcome to give me any feedbacks and suggestions, cheers

**Comment by Lucashuang0802** [comment]
Do I have to resolve the conflict? I think someone gets change on the notification portion and get approved a few days before?

**Comment by nlutsenko** [comment]
Yes, please!
I'll get to it today.
Also - if you could squash commits into a single one or at least squash all the changes into a commit per file it would be very very helpful...
The code is incredibly hard to review otherwise, as it requires to go back and forth between two or more commits that are about the same file.

**Comment by Lucashuang0802** [comment]
Got it.

**Comment by Lucashuang0802** [comment]
I create PR #58 for squashing all the commits and resolving all the conclicts

**Comment by Lucashuang0802** [comment]
Link #73

**Comment by nlutsenko** [comment]
Superseeded by #73

**Pull request closed without merging**
