### PR TITLE
Add afterLogout trigger docs

### PR DESCRIPTION
**Pull request by mtrezza**
Todo before merging:
- Adapt line `*Available only on parse-server cloud code starting 3.10.0*` if necessary.

### CODE REVIEW

**Comment by mtrezza** [comment]
Docs for https://github.com/parse-community/parse-server/pull/6217

**Comment by dplewis** [comment]
Next release will be 4.0.0. It’s going to be massive, trust me

**Review by TomWFox — APPROVED** [review]
Looks good to me. We'll wait to merge until the server pr is merged and a release made.

Thanks for taking the time to document!

**Comment by mtrezza** [comment]
@TomWFox Thanks, just as reminder for us:

- Adapt line *Available only on parse-server cloud code starting 3.10.0* if necessary.

**Comment by TomWFox** [comment]
Merging as 3.10 has been released.

**Comment by TomWFox** [comment]
@mtrezza there is a merge conflict - I don't have time to resolve it now so if you can that would be great or I'll get to it in a day or so

**Comment by mtrezza** [comment]
@TomWFox let me take a look at it...

**Comment by mtrezza** [comment]
@TomWFox the merge conflict is the auto-generated `bundle.js`. I suggest to keep either of the versions and run webpack again to generate the new `bundle.js`, then merge. I don't have the access rights for that, do you?

**Comment by TomWFox** [comment]
Not sure, we did have this problem before, I seem to remember we just kept the version from the upstream master but I'm not certain.

**Comment by mtrezza** [comment]
@TomWFox What I could do is to rebase and submit a new PR, to be on the safe side. I think I won't be able to push to this branch after rebase. What do you think?

**Comment by dplewis** [comment]
If I remember correctly we want to keep the upstream master bundle.js files since it gets generated.

@acinader explained the process here https://github.com/parse-community/docs/pull/606#issuecomment-475373541

**Comment by mtrezza** [comment]
Thanks @dplewis, resolved by keeping upstream changes, ready to merge.

And you were right, 3.10 was massive! 👏

**Comment by dplewis** [comment]
Should we add it to the gitignore since it will be generated anyway? Sorry not too familiar with the bundle process.

**Comment by mtrezza** [comment]
@dplewis gitignore makes sense to me, file is generated on every run.

**Pull request merged**
