### PR TITLE
Docs for GQL query and mutation aliases

### PR DESCRIPTION
**Pull request by BufferUnderflower**
See parse-community/parse-server#6257 parse-community/parse-server#6258

### CODE REVIEW

**Review by davimacedo — APPROVED** [review]
It looks good to me. Thanks for the PR @BufferUnderflower !

**Comment by TomWFox** [comment]
We'll wait to merge until after the next Parse Server release.

**Comment by TomWFox** [comment]
@Moumouls not sure whether this PR aligns with yours or not?

**Comment by davimacedo** [comment]
@TomWFox I think we should merge this one.

**Comment by TomWFox** [comment]
Ok thanks @davimacedo :)

**Pull request merged**
