### PR TITLE
Fixed issues #21: Provide missing Swift doc

### PR DESCRIPTION
**Pull request by Lucashuang0802**
Link issues: #41 #58 
@nlutsenko

### CODE REVIEW

**Comment by Lucashuang0802** [comment]
@nlutsenko Sorry for creating another PR. That's much convenient. Please merge it. I will delete those two previous PR.

**Comment by nlutsenko** [comment]
Sure, np.
Looks great! Merging in!

**Comment by Lucashuang0802** [comment]
Thanks! @nlutsenko Nice to work with you

**Comment by Lucashuang0802** [comment]
Just a question, how can I act as a contributor.

**Comment by nlutsenko** [comment]
Hmm... Not sure what you mean.
Act as a contributor on ... ?

**Comment by Lucashuang0802** [comment]
Just silly thought on it. I saw that people who contributed will appear on the *Contributor* list. Anyway, just ignore it. SourceTree makes me like a Git dumb.

**Comment by nlutsenko** [comment]
To the best of my knowledge we don't have a maintained contributor list as of right now.
(if you find one - please point me to it)

If we would have any list like that - you'll be on that list, for sure.

**Comment by Lucashuang0802** [comment]
Anyway, thanks for this opportunity to let me practice how to take advantage of this powerful tool.

**Pull request merged**
