### PR TITLE
Removed MongoRocks from the parse-server guide

### LINKED ISSUE #718: 📙 remove info about mongorocks
__Link to section:__
Please provide a specific link to the section in question. In the docs, you can click on a heading and then copy the relative link from the address bar.

__What is the issue?__
Parse-community/parse-server#6468

__Can you propose a solution?__
What changes do you think should be made? Have you considered multiple solutions? Will this be suitable for all use cases?

### PR DESCRIPTION
**Pull request by hej2010**
Issue #718 and from [here](https://community.parseplatform.org/t/using-mongodb-with-rocksdb/1543/6)

closes #718

### CODE REVIEW

**Comment by mtrezza** [comment]
Thanks for opening this PR!

Did you check whether there are any links to that file that should also be removed?

**Comment by hej2010** [comment]
Now I did :) No other references to it that I can find

**Comment by mtrezza** [comment]
Thanks!

@TomWFox How is https://docs.parseplatform.org/parse-server/guide/#using-mongodb--rocksdb composed? Is there another reference that needs to be removed to not make it appear in the table of contents?

**Comment by TomWFox** [comment]
That should do the trick as is, thanks for the PR @hej2010!

**Comment by TomWFox** [comment]
Should we be adding in a note about WiredTiger as well as removing the note about MongoRocks?

**Comment by mtrezza** [comment]
The current Parse Server version still supports both storage engines of MongoDB (MMAPv1, WiredTiger).

The next version of Parse Server will drop support for MongoDB 3.6 and Node 8 - 10. In fact we should remove these requirements because they change every year and we have a compatibility table in the Parse Server README, which makes more sense.

**Review by TomWFox — APPROVED** [review]
Looks good to me then 👍

**Review by mtrezza — APPROVED** [review]

**Pull request merged**
