### PR TITLE
Defined schemas updates

### LINKED ISSUE #872: 📙 Add defined schema docs
The original PR to extend the docs is not being actively worked on anymore.

### PR DESCRIPTION
**Pull request by epietrowicz**
I'm hoping to help get the schema documentation merged in as I have been using this feature in production for some time now. 

I stepped through #863 and accounted for each item of feedback.

Closes: #872

I want to avoid interfering with @Moumouls's existing work as he make all the progress here. Let me know if there's a better way to go about getting this merged in which credits him.

### CODE REVIEW

**Comment by Moumouls** [comment]
Hi @epietrowicz 

Happy to hear that you use defined schema in production, I'll take a look to your suggestions. 

I didn't get the time to finalize docs.

Also I'll be happy to get your feedback on my first try, since I'm little bit biased as the creator of this feature !

We definitely need to merge this asap, thanks for your contribution !

**Comment by Moumouls** [comment]
Hi @epietrowicz everything looks good but you pushed a lockfile V2. Could you just restore the package lock to current one (v1), to keep V1 during `npm i` just switch to `Node 14` (you can use nvm).

@mtrezza could the documentation be updated to use lockfile v2 ?

@mtrezza if you have additional feedbacks on docs ?

**Comment by mtrezza** [comment]
I think we can bump this to lockfile v2; npm is only used internally, but we don't have a CI here, so whether we change we should probably keep an eye on it.

Docs look amazing, seems to have been quite a bit of work; if there are any minor thing to improve like formatting we'll probably see that easier once it's published - so far looks great.

**Comment by Moumouls** [comment]
@epietrowicz we just need to wait https://github.com/parse-community/docs/pull/910 then you will need to merge gh-pages into this branch and we will be good to go !

**Comment by mtrezza** [comment]
#910 has been merged, @epietrowicz could you rebase and resolve the conflicts?

**Comment by Moumouls** [comment]
PR continued: https://github.com/parse-community/docs/pull/912

**Comment by mtrezza** [comment]
Can this one be closed then?

**Comment by Moumouls** [comment]
Yes @mtrezza

**Pull request closed without merging**
