### PR TITLE
Add dot notation key in query examples

### PR DESCRIPTION
**Pull request by acinader**
see https://github.com/parse-community/parse-server/pull/4399

### CODE REVIEW

**Review by montymxb — DISMISSED** [review]
Additions look good. We probably want an example for the ios sdk while we're at it though.

**Comment by acinader** [comment]
@montymxb can you take another look at this

**Comment by TomWFox** [comment]
I've fixed a couple of formatting issues. It makes sense to get this merged in even without the iOS example and then we can open an issue.

**Comment by TomWFox** [comment]
@acinader are you happy for me to merge this in?

**Comment by acinader** [comment]
yeah, getting my doc improvement from november of 17 merged in would make me happy.  thanks for asking ;)

**Comment by TomWFox** [comment]
We're really prompt here ;)

**Comment by TomWFox** [comment]
Also I noticed that only the PHP docs have section headings for the different types of query constraints which is much easier to navigate than the other docs - I think I'll open an issue/pr for this too.

**Pull request merged**
